#!/bin/bash

sudo yum install httpd mariadb-server mariadb mysql-server php php-mysql php libapache2-mod-php php-mysql php-cgi php-gd php-zip php-xml php-xmlrpc php-curl php-json php-mbstring php-cli --yes
sudo systemctl start httpd.service
iptables -A IN_public_allow -p tcp -m tcp --dport 80 -m conntrack --ctstate NEW -j ACCEPT
iptables-save
sudo yum install http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
sudo systemctl start mysqld
sudo mysql_secure_installation
sudo systemctl start mariadb
sudo systemctl restart httpd.service
exit
