#!/bin/bash

sudo yum install httpd httpd-tools mysql mysql-server php php-cgi php-gd php-zip php-xml php-xmlrpc php-curl php-common php-json php-mbstring php-cli -y
sudo systemctl start mysqld
sudo systemctl start httpd
sudo systemctl start php-fpm
sudo mkdir /var/www/test.ru
sudo yum install curl
cd /tmp
curl -O https://ru.wordpress.org/latest-ru_RU.tar.gz
tar xzvf latest-ru_RU.tar.gz
sudo cp -a /tmp/wordpress/. /var/www/test.ru/

exit
