#!/bin/bash

sudo yum install httpd httpd-tools mysql mysql-server php php-cgi php-gd php-zip php-xml php-xmlrpc php-curl php-common php-json php-mbstring php-cli -y
sudo systemctl start mysqld
sudo systemctl start httpd
sudo systemctl start php-fpm
sudo touch /etc/apache2/sites-available/test.ru.conf
echo "<VirtualHost *:80>" > tee /etc/apache2/sites-available/test.ru.conf
echo "	ServerName test.ru" | sudo tee -a /etc/apache2/sites-available/test.ru.conf
echo "	ServerAdmin test@host" | sudo tee -a /etc/apache2/sites-available/test.ru.conf
echo "	DocumentRoot /var/www/test.ru" | sudo tee -a /etc/apache2/sites-available/test.ru.conf
echo "	ErrorLog \${APACHE_LOG_DIR}/$errlog.log" | sudo tee -a /etc/apache2/sites-available/test.ru.conf
echo "	CustomLog \${APACHE_LOG_DIR}/$acclog.log combined" | sudo tee -a /etc/apache2/sites-available/test.ru.conf
echo "</VirtualHost>" | sudo tee -a /etc/apache2/sites-available/test.ru.conf
sudo mysql -u root -e "CREATE DATABASE word;"
sudo mysql -u root -e "CREATE USER 'ss'@'localhost' IDENTIFIED BY '123';"
sudo mysql -u root -e "GRANT ALL PRIVILEGES ON word.* TO 'ss'@'localhost';"
sudo mysql -u root -e "FLUSH PRIVILEGES;"
sudo mkdir /var/www/test.ru
sudo yum install curl
cd /tmp
curl -O https://ru.wordpress.org/latest-ru_RU.tar.gz
tar xzvf latest-ru_RU.tar.gz
sudo cp -a /tmp/wordpress/. /var/www/test.ru/
sudo ln -s /etc/httpd/sites-available/test.ru.conf /etc/httpd/sites-enabled/test.ru.conf
mv /etc/httpd/sites-available/test.ru.conf /etc/httpd/conf.d/
sudo systemctl restart httpd

exit
