#!/bin/bash

sudo apt-get install apache2 mariadb-server mariadb-client php libapache2-mod-php php-mysql php-cgi php-gd php-zip php-xml php-xmlrpc php-curl php-json php-mbstring php-cli --yes
sudo apt-get install ufw
sudo ufw allow in 80/tcp
sudo a2enmod rewrite; sudo sed -i "s/AllowOverride None/AllowOverride ALL/" /etc/apache2/apache2.conf; sudo systemctl restart apache2
sudo mysql_secure_installation --yes
sudo mysql -u root -e "CREATE DATABASE wp_database;"
sudo mysql -u root -e "CREATE USER 'wp_user'@'localhost' IDENTIFIED BY '123';"
sudo mysql -u root -e "GRANT ALL PRIVILEGES ON wp_database.* TO 'wp_user'@'localhost';"
sudo mysql -u root -e "FLUSH PRIVILEGES;"
mkdir /var/www/test.ru
sudo apt-get install curl
cd /tmp
curl -O https://ru.wordpress.org/latest-ru_RU.tar.gz
tar xzvf latest-ru_RU.tar.gz
cp -a /tmp/wordpress/. /var/www/test.ru/
echo "<VirtualHost *:80>" > /var/apache2/sites-available/test.ru.conf
echo "ServerName test.ru" > /var/apache2/sites-available/test.ru.conf
echo "ServerAlias www.test.ru" > /var/apache2/sites-available/test.ru.conf
echo "ServerAdmin admin@example.com" > /var/apache2/sites-available/test.ru.conf
echo "DocumentRoot /var/www/test.ru" > /var/apache2/sites-available/test.ru.conf
echo "<Directory /var/www/test.ru>" > /var/apache2/sites-available/test.ru.conf
echo "Options -Indexes +FollowSymLinks" > /var/apache2/sites-available/test.ru.conf
echo "AllowOverride ALL" > /var/apache2/sites-available/test.ru.conf
echo "</Directory>" > /var/apache2/sites-available/test.ru.conf
echo "ErrorLog ${APACHE_LOG_DIR}/test.ru-error.log" > /var/apache2/sites-available/test.ru.conf
echo "CustomLog ${APACHE_LOG_DIR}/test.ru-access.log combined" > /var/apache2/sites-available/test.ru.conf
echo "</VirtualHost>" > /var/apache2/sites-available/test.ru.conf
sudo a2ensite test.ru
systemctl restart apache2.service

exit