#!/bin/bash

sudo apt-get install apache2 mariadb-server mariadb-client php libapache2-mod-php php-mysql php-cgi php-gd php-zip php-xml php-xmlrpc php-curl php-json php-mbstring php-cli --yes
sudo apt-get install ufw
sudo ufw allow in 80/tcp
sudo a2enmod rewrite; sudo sed -i "s/AllowOverride None/AllowOverride ALL/" /etc/apache2/apache2.conf; sudo systemctl restart apache2
exit
